---
title: "MiSeq-239"
output:
  html_notebook:
    df_print: paged
    number_sections: yes
    theme: lumen
    toc: yes
    code_folding: hide
---

<style>
  html {
    font-size: 16pt;
  }
  
  body {
    font-size: 16pt;
  }
  
  h1 {
    font-size: 2.2rem;
  }
  
  h2 {
    font-size: 2rem;
  }
  
  h3 {
    font-size: 1.8rem;
  }
  
  h4 {
    font-size: 1.4rem;
  }
  
</style>

# Alapha Diversity Regression Effect Size Plots {.tabset}
## Clustering Level
Data Clustered at the Genus level.

## Setup {.tabset}

### [Close]

### Start Conda ENV
```{r}
startCondaEnv('alphadiv')
```

### Set Knitr Options
```{r}
library(rmarkdown)
library(knitr)

opts_chunk$set(
  echo=TRUE,
  dpi=300,
  fig.width=12
  )
```

### Load Libraries
```{r}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(ggbeeswarm)
library(openxlsx)
library(DT)
library(pheatmap)
library(kableExtra)
library(vegan)
library(nlme)

### Custom libraries that can be loaded from GitHub
source('~/utilities/analysis-utilities/general_asv_data_analysis_utilities.R')
source('~/utilities/analysis-utilities/alpha_div_utilities.R')
```


### Set Paths
```{r}
source('./set_paths.R')
```

### Load Data
```{r}
filename = file.path(tables_dir, 'miseq-239_asv_clust_alpha_diversity_master_tables.xlsx')

all_master_table = readWorkbook(filename, sheet='All Subgroups')
age_lt_90_master_table = readWorkbook(filename, sheet='Age < 90')
amd_only_master_table = readWorkbook(filename, sheet='AMD Only')

sample_metadata = read.delim(
  file.path(metadata_dir, 'miseq-239_metadata_CNV_GA.tsv'), 
  stringsAsFactors=F
  )

source(file.path(metadata_dir, 'observational_variables.R'))

filename = file.path(tables_dir, 'miseq-239_asv_clust_alpha_div_regression_stats.xlsx')
pvalues = readWorkbook(filename, sheet='Unadjusted P-Values')
effect_sizes = readWorkbook(filename, sheet='Effect Sizes')

```


```{r}
pvalues = 
  pvalues %>%
  remove_rownames() %>%
  column_to_rownames('Index') %>%
  t() %>% data.frame() %>%
  rownames_to_column('Predictor')

effect_sizes = 
  effect_sizes  %>%
  remove_rownames() %>%
  column_to_rownames('Index') %>%
  t() %>% data.frame() %>%
  rownames_to_column('Predictor')
```


```{r}
response_vars = colnames(pvalues) %>% setdiff('Predictor')

for (var in response_vars)
{
  plotEffectSizes(
  pvals,
  effect_sizes,
  response_var=var,
  effect_size_template='(log) Regression Cofficient',
  category_label='Observational Variables'
) 
}
```


```{r}
# annotations = data.frame(
#   xloc = 11,
#   yloc = -2.5,
#   text="negative relationship"
# )

plotEffectSizes(
  pvals,
  effect_sizes,
  response_var='All_Observed',
  effect_size_template='(log) Regression Cofficient',
  category_label='Observational Variables'
) 

# + geom_label(
#   data=annotations,
#   aes(x=xloc, y=yloc, label=text),
#   color='black'
# )

```

