#!/bin/bash

#Rscript -e "rmarkdown::render('$1', output_dir='../reports', output_format='html_notebook')"
Rscript -e "rmarkdown::render('$1')"

if [[ -d "../reports" ]]; then
  mv *.html ../reports
else
  echo "no reports folder"
fi

