---
title: "MiSeq-239"
output:
  html_notebook:
    df_print: paged
    number_sections: yes
    theme: lumen
    toc: yes
    code_folding: hide
---

<style>
  html {
    font-size: 16pt;
  }
  
  body {
    font-size: 16pt;
  }
  
  h1 {
    font-size: 2.2rem;
  }
  
  h2 {
    font-size: 2rem;
  }
  
  h3 {
    font-size: 1.8rem;
  }
  
  h4 {
    font-size: 1.4rem;
  }
  
</style>

# F B Analysis; Pair Tests {.tabset}

## Setup

### Start Conda ENV
```{r}
startCondaEnv('alphadiv')
```

### Set Knitr Options
```{r}
library(rmarkdown)
library(knitr)

opts_chunk$set(
  echo=TRUE,
  dpi=300,
  fig.width=12
  )
```

### Load Libraries
```{r}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(ggbeeswarm)
library(openxlsx)
library(DT)
library(pheatmap)
library(kableExtra)
library(vegan)
library(nlme)

### Custom libraries that can be loaded from GitHub
source('~/utilities/analysis-utilities/general_asv_data_analysis_utilities.R')
source('~/utilities/analysis-utilities/alpha_div_utilities.R')
```
### Set Paths
```{r}
project_dir = "~/miseq-239"
dada2_table_dir = file.path(project_dir, "processed_data")
metadata_dir = file.path(project_dir, "metadata")
analysis_dir = file.path(project_dir, 'analysis/f2b_ratio')
tables_dir = file.path(analysis_dir, 'tables')
```

### Load Data
```{r}
fb_master_table = read.xlsx(file.path(tables_dir, 'miseq-239_F_B_master_table.xlsx'))

age_lt_90_master_table = fb_master_table %>% filter(Age<90)
amd_only_master_table = fb_master_table %>% filter(CaseString=='AMD')

# grep('ARMS', colnames(sample_metadata), value=T)
grep('ARMS', colnames(fb_master_table), value=T)
```


### Variables of interest
```{r}
variables_of_interest = list(
  CaseString = list(
    covariate_of_interest='CaseString',
    control='Control',
    case='AMD',
    lables=list(reference='Control', comparison='AMD')
  ),
  ARMS2rs10490924 = list(
    covariate_of_interest='ARMS2rs10490924',
    control='GG',
    case='TT',
    labels=list(reference='Non-Risk', comparison='Risk')
    ),
  CFHrs1061170 = list(covariate_of_interest='CFHrs1061170',
    control='TT',
    case='CC',
    labels=list(reference='Non-Risk', comparison='Risk')
    ),
  CFHrs10737680 = list(
    covariate_of_interest='CFHrs10737680',
    control='CC',
    case='AA',
    labels=list(reference='Non-Risk', comparison='Risk')
    ),
  SKIV2Lrs429608 = list(
    covariate_of_interest='SKIV2Lrs429608',
    control='AA',
    case='GG',
    labels=list(reference='Non-Risk', comparison='Risk')
    ),
  GA_No_CNV_Either_Eye = list(
    covariate_of_interest='GA_No_CNV_Either_Eye',
    control=0,
    case=1,
    labels=list(reference='Healthy', comparison='Disease')
    ),
  CNV_Either_Eye = list(
    covariate_of_interest='CNV_Either_Eye',
    control=0,
    case=1,
    labels=list(reference='Healthy', comparison='Disease')
    ),
  Age = list(
    covariate_of_interest='Age',
    control='',
    case=''
    ),
  Gender = list(
    covariate_of_interest='Gender',
    control='F',
    case='M',
    labels=list(reference='F', comparison='M')
    ),
  AREDS = list(
    covariate_of_interest='AREDS',
    control='N',
    case='Y',
    labels=list(reference='N', comparison='Y')
    )
  )
```


### Set Factor Levels
```{r}
setFactors = function(df)
{
  for (var in variables_of_interest)
  {
    name = var$covariate_of_interest
    case = var$case
    control = var$control
    # print(sprintf('name: %s, case: %s, control: %s', name, case, control))
  
    if (case != '' & control != '')
    {
      # print('ok')
      df = mutate(df, !!name := factor(!!as.name(name), levels=c(control, case)))
    }
  
  }
  
  return(df)
}

fb_master_table = setFactors(fb_master_table)
age_lt_90_master_table = setFactors(fb_master_table %>% filter(Age<90))
amd_only_master_table = setFactors(fb_master_table %>% filter(CaseString=='AMD'))

```


## Pair Tests

#### Initialize Table

```{r}
pval_names = lapply(variables_of_interest, function(x)
{
  pval_name = paste0(x$covariate_of_interest, x$case)
})

pval_names
```

```{r}
all_pair_stats = data.frame(
  TestGroup=character(),
  TestVariable=character(),
  Reference=character(),
  Comparison=character(),
  Firmicutes=numeric(),
  Bacteroidetes=numeric(),
  F2B_Ratio=numeric(),
  LogF2B_Ratio=numeric(),
  FB_Index=numeric()
  )

age_lt_90_pair_stats = all_pair_stats
amd_only_pair_stats = all_pair_stats

adjusted_pair_stats = all_pair_stats
adjusted_age_lt_90_pair_stats = all_pair_stats
adjusted_amd_only_pair_stats = all_pair_stats


```



```{r}
firmicutes_mw = wilcox.test(
  Firmicutes~CaseString, 
  data=fb_master_table,
  alternative='two.sided'
  )

bacteroidetes_mw = wilcox.test(
  Bacteroidetes~CaseString, 
  data=fb_master_table,
  alternative='two.sided'
  )

f2b_ratio_mw = wilcox.test(
  F2B_Ratio~CaseString, 
  data=fb_master_table,
  alternative='two.sided'
  )

log_f2b_ratio_mw = wilcox.test(
  LogF2B_Ratio~CaseString, 
  data=fb_master_table,
  alternative='two.sided'
  )

fb_index_mw = wilcox.test(
  FB_Index~CaseString, 
  data=fb_master_table,
  alternative='two.sided'
  )

all_pair_stats %<>%
  add_row(
    TestGroup='All',
    TestVariable='CaseString',
    Reference='Control',
    Comparison='Case',
    Firmicutes=firmicutes_mw$p.value,
    Bacteroidetes=bacteroidetes_mw$p.value,
    F2B_Ratio=f2b_ratio_mw$p.value,
    LogF2B_Ratio=log_f2b_ratio_mw$p.value,
    FB_Index=fb_index_mw$p.value
  )
```

#### Age < 90
```{r}
firmicutes_mw = wilcox.test(
  Firmicutes~CaseString, 
  data=age_lt_90_master_table,
  alternative='two.sided'
  )

bacteroidetes_mw = wilcox.test(
  Bacteroidetes~CaseString, 
  data=age_lt_90_master_table,
  alternative='two.sided'
  )

f2b_ratio_mw = wilcox.test(
  F2B_Ratio~CaseString, 
  data=age_lt_90_master_table,
  alternative='two.sided'
  )

log_f2b_ratio_mw = wilcox.test(
  LogF2B_Ratio~CaseString, 
  data=age_lt_90_master_table,
  alternative='two.sided'
  )

FB_Index_mw = wilcox.test(
  FB_Index~CaseString, 
  data=age_lt_90_master_table,
  alternative='two.sided'
  )

all_pair_stats %<>%
  add_row(
    TestGroup='Age_lt_90',
    TestVariable='CaseString',
    Reference='Control',
    Comparison='Case',
    Firmicutes=firmicutes_mw$p.value,
    Bacteroidetes=bacteroidetes_mw$p.value,
    F2B_Ratio=f2b_ratio_mw$p.value,
    LogF2B_Ratio=log_f2b_ratio_mw$p.value,
    FB_Index=fb_index_mw$p.value
  )
```

#### AMD Only
```{r}
amd_only_variables = variables_of_interest
amd_only_variables['Gender'] = NULL
amd_only_variables['CaseString'] = NULL
amd_only_variables['Age'] = NULL
names(amd_only_variables)
```
```{r}
amd_only_pair_stats = data.frame(
  TestGroup=character(),
  TestVariable=character(),
  Reference=character(),
  Comparison=character(),
  Firmicutes=numeric(),
  Bacteroidetes=numeric(),
  F2B_Ratio=numeric(),
  LogF2B_Ratio=numeric(),
  FB_Index=numeric()
  )

```


```{r}
for (var in amd_only_variables)
{
  test_variable = var$covariate_of_interest
  case = var$case
  control = var$control
  
  print(test_variable)
  formula_rhs = paste0(' ~ ', test_variable)
  
  temp_master_table = 
    amd_only_master_table %>%
    filter(!!as.name(test_variable) %in% c(var$case, var$control))
  
  if (!all(c(case, control) %in% temp_master_table[[test_variable]]))
  {
    print("not all levels present. skipping...")
    next
  }
  
  firmicutes_mw = wilcox.test(
    as.formula(paste0('Firmicutes', formula_rhs)),
    data=temp_master_table,
    alternative='two.sided'
    )
  
  bacteroidetes_mw = wilcox.test(
    as.formula(paste0('Bacteroidetes', formula_rhs)),
    data=temp_master_table,
    alternative='two.sided'
    )
  
  f2b_ratio_mw = wilcox.test(
    as.formula(paste0('F2B_Ratio', formula_rhs)),
    data=temp_master_table,
    alternative='two.sided'
    )
  
  log_f2b_ratio_mw = wilcox.test(
    as.formula(paste0('LogF2B_Ratio', formula_rhs)),
    data=temp_master_table,
    alternative='two.sided'
    )
  
  print(as.formula(paste0('FB_Index', formula_rhs)))
  fb_index_mw = wilcox.test(
    as.formula(paste0('FB_Index', formula_rhs)),
    data=temp_master_table,
    alternative='two.sided'
    )
  
  amd_only_pair_stats %<>%
    add_row(
      TestGroup='AMD_Only',
      TestVariable=test_variable,
      Reference=var$labels$reference,
      Comparison=var$labels$comparison,
      Firmicutes=firmicutes_mw$p.value,
      Bacteroidetes=bacteroidetes_mw$p.value,
      F2B_Ratio=f2b_ratio_mw$p.value,
      LogF2B_Ratio=log_f2b_ratio_mw$p.value,
      FB_Index=fb_index_mw$p.value
    )
  
}


# adjusted_amd_only_pair_stats = amd_only_pair_stats
# 
# for (pval_col in c(
#   'Firmicutes', 
#   'Bacteroidetes', 
#   'F2B_Ratio',
#   'LogF2B_Ratio',
#   'FB_Index'
#   ))
# {
#   adjusted_amd_only_pair_stats[[pval_col]] = p.adjust(amd_only_pair_stats[[pval_col]], method='fdr')
# }

```

```{r}
all_pair_stats =
  all_pair_stats %>%
  add_row(!!!amd_only_pair_stats)
```



```{r}
filename = file.path(tables_dir, 'miseq-239_fb_pair_tests_unadjusted.xlsx')
write.xlsx(
  all_pair_stats,
  file=filename,
  quote=F
)
```

